### ISSUE TITLE
Keep W-iFi

### ISSUE THREAD

**Issue by untuned** [rern/RuneAudio#17]
Will Wi-Fi still work after running this?  I don't have an ethernet cable at home, so it's easier if I can keep it enabled.

**Comment by rern** [comment]
It is just an example of setup script. Don't use it unless you know exactly what it does line by line. You should install each addon one at a time through [Addons](https://github.com/rern/RuneAudio_Addons)

**Comment by untuned** [comment]
> It is just an example of setup script. Don't use it unless you know exactly what it does line by line. You should install each addon one at a time through [Addons](https://github.com/rern/RuneAudio_Addons)

Thanks for the help.
