### ISSUE TITLE
how to query internet to fill missing tag in mp3 files

### ISSUE THREAD

**Issue by Barlafuss** [rern/RuneAudio#20]
having many mp3 files without album year tag inside, may i use kid3-cli to add this info? how ?  Thanks

**Comment by rern** [comment]
In RuneAudio+R:
folder icon > Tag
or track view > coverart > Tag

**Comment by Barlafuss** [comment]
mm, not sure What You mean.
I was searching something like this:
for item in Albums_No_Date:
    Path="'"+item+"'"
    subprocess.call('kid3-cli -c autoimport %s' %(Path+"/"+"*.mp3"), shell=True)
It works for my need

**Comment by rern** [comment]
It meant in context of [RuneAudio+R e3](https://www.runeaudio.com/forum/runeaudio-r-e3-t7014.html) which this repo is for.
